1 entries in records
Started running calling sequence 1
Traceback (most recent call last):
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\common_utils\audit.py", line 152, in wrapper
    source_count, insert_count, update_count = function(*args, **kwargs)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\clicktoch\db.py", line 22, in click_to_ch
    table_name = row.targettablename
                 ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Pandas' object has no attribute 'targettablename'

Finished d_region in 0.24 seconds
Finished running calling sequence 1 in 0.2445090999826789 seconds
