1 entries in records
Started running calling sequence 1
Executing: EXEC dbo.usp_d_category;
Error executing stored procedure usp_d_category: (psycopg2.errors.SyntaxError) syntax error at or near "EXEC"
LINE 1: EXEC dbo.usp_d_category;
        ^

[SQL: EXEC dbo.usp_d_category;]
(Background on this error at: https://sqlalche.me/e/20/f405)
Error occurred: 'Pandas' object has no attribute 'targettablename'
Traceback (most recent call last):
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\silvertogold\__main__.py", line 67, in <module>
    main(cli_args)
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\silvertogold\__main__.py", line 59, in main
    sp_caller.call_sp(row)
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\common_utils\timing.py", line 49, in wrapper
    logger.info("Finished %s in %.2f seconds", record.targettablename, (time_end - time_start))
                                               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Pandas' object has no attribute 'targettablename'
